### ISSUE TITLE
当工程下有submodule时候，在主repo生成tag commit，会生成到submodule的input里面去

### ISSUE THREAD

**Issue by zhangzhenfei** [Mongkii/Commit-Tagger#1]
当工程下有submodule时候，在主repo生成tag commit，会生成到submodule的input里面去

![image](https://user-images.githubusercontent.com/6110215/84558589-a71a2780-ad66-11ea-9487-09c0112e6589.png)

**Comment by zhangzhenfei** [comment]
实际上我选中的是m-suntrip生成tag，结果生成到了PiUI-basic中

**Comment by Mongkii** [comment]
收到，近期会处理这个问题

**Comment by zhangzhenfei** [comment]
> 收到，近期会处理这个问题

大佬，帮忙抽时间改改这个问题 @Mongkii

**Comment by Mongkii** [comment]
已修复，更新到 2.0.2 版应该就没问题了 @zhangzhenfei
