### ISSUE TITLE
当显示源代码存储库和多个submodule时候，图标显示不出来

### ISSUE THREAD

**Issue by zhangzhenfei** [Mongkii/Commit-Tagger#4]
![image](https://user-images.githubusercontent.com/6110215/96663069-7a17fa00-1382-11eb-9908-ad0afc1c2135.png)

**Comment by Mongkii** [comment]
感谢反馈，我周末看下

**Comment by Mongkii** [comment]
已修复，更新到 2.1.4 版即可
