### ISSUE TITLE
多个submodule的时候，当在源代码管理中，点击第一存储库，生成的prefix会生成到第二个库中

### ISSUE THREAD

**Issue by zhangzhenfei** [Mongkii/Commit-Tagger#5]
![image](https://user-images.githubusercontent.com/6110215/102594706-82599f00-4151-11eb-989a-ae613b845022.png)
![image](https://user-images.githubusercontent.com/6110215/102594747-90a7bb00-4151-11eb-9a36-99937a2957e6.png)

**Comment by Mongkii** [comment]
👌 我这周看下

**Comment by Mongkii** [comment]
这个问题没法稳定复现
我先尝试修改了，你安装 2.1.5 版本之后如果没问题的话就把这个 issue 关掉吧
